
# $ python main.py --dataset mnist --input_height=28 --output_height=28 --train
# $ python main.py --dataset celebA --input_height=108 --train --crop

params:
  dataset: celebA
  input_height: 108
  train: crop

  # dataset: mnist
  # input_height: 28
  # output_height: 28
  # train: train

testing_benchmark:
  generator:
    relu: True
    lrelu: True
    tanh: True
    pooling: True
    batch_normalization: True

  degenerator:
    relu: True
    lrelu: True
    tanh: True
    pooling: True
    batch_normalization: True
