# $ python main.py --dataset celebA --input_height=108 --train --crop

params:
  dataset: celebA
  input_height: 108
  train: crop

  # dataset: mnist
  # input_height: 28
  # output_height: 28
  # train: train

paths:
  path_to_runs: Documents/dcgan_runs
  path_to_checkpoints: Documents/dcgan_runs

testing_benchmark:
  batch_norm: True
  generator:
    relu: True
    lrelu: False
    tanh: False

  degenerator:
    relu: False
    lrelu: True
    tanh: False
    pooling: False

random_vector:
    uniform: True
    uniform100: False
    normal: False